# -*- coding: utf-8 -*-
"""convert_h5_to_json.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k0OlVSM01zsZLrADl8rBzushxgdan0V9
"""

!pip install tensorflowjs

import tensorflow as tf
import tensorflowjs as tfjs
import os


model_path = "skin_disease_model.h5"
model = tf.keras.models.load_model(model_path)

output_dir = "tfjs_model"
os.makedirs(output_dir, exist_ok=True)
tfjs.converters.save_keras_model(model, output_dir)

print(f"Converted successfully! Files saved in '{output_dir}'.")

!zip -r tfjs_model.zip tfjs_model

from google.colab import files
files.download("tfjs_model.zip")